# compose/development/django/Dockerfile
FROM python:3.11

WORKDIR /app

COPY . .

RUN pip install --upgrade pip && pip install -r requirements/development.txt

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]