# Compose/development/Dockerfile.db
# Using Postgres
FROM postgres:16

# Set environment variables
ENV POSTGRES_DB=${DB_NAME}
ENV POSTGRES_USER=${DB_USER}
ENV POSTGRES_PASSWORD=${DB_PASSWORD}

# Expose the PostgreSQL port
EXPOSE 5432